### ISSUE TITLE
Improve instructions for Windows setup.

### ISSUE THREAD

**Issue by jamieburchell** [RemoteDebug/remotedebug-ios-webkit-adapter#106]
All I actually needed to do to get this working on 64 bit Windows with iOS 11 was to downloaded the zip file mentioned in point 1, run the exe and allow the firewall rule.

The README had me confused. It says "All dependencies should be bundled. You should be good to go." but then goes on to say for iOS 10 and 11 https://github.com/artygus/ios-webkit-debug-proxy-win32 might be out of date (that project seems dead?).

Then, for 64 bit Windows you need to download "additional" assets (additional to what?) and extract to node_modules. This had me confused because nowhere did it say I needed to install Node? Step 2 says `npm install ...` so I assumed I needed Node. I didn't, and I didn't need to create any paths under %AppData%.

EDIT: Although this gave me the DOM inspector and manipulation, the console did not work. So I hunted further, installed Node and the npm package, moved the referenced files to x64 but just kept getting iosAdapter.getTargets and nothing in Chrome. It seems the README is incomplete - there is a further step (4): https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79#issuecomment-351472710

**Comment by auchenberg** [comment]
@jamieburchell I'd be more than happy to accept a PR for an readme update.

**Comment by jamieburchell** [comment]
Completely understand your point, but I don't know enough about the various projects, requirements and potential nuances to be able to update the README.  I'm still muddling through myself.

**Comment by dkeulen** [comment]
+1 i have the same issue.
Followed all instructions, the only thing i get is the command line saying:

iosAdapter.getTargets, over and over.

Then i also do not see anything under chrome://inspect/#devices, until i add a portforward in the remote devices tab, than i see "Target (RemoteDebug iOS Webkit Adapter)" in my remote targets under chrome://inspect/#devices, but i do not see that remote target in my remote target debugger (chrome) itself (it does say "New websocket connection to /devtools/browser when i add a portforwarding).

SO what Jamie is saying is: i think the windows guide needs an update because it seems incomplete/not working like it is now.

Don't get us wrong, we followed the guide and where able to perform all the actions, but eventually it is not working.

windows 10,
webkit-debugger 1.8-x64 (as 1.8.1 does not privode the files needed in the guide)
chrome dev tools, latest
ipad 4, ios 10.3

![2018-08-16_17-01-56](https://user-images.githubusercontent.com/782885/44216883-5fc8ad00-a176-11e8-9d6f-4047b7fbe1e5.gif)

**Comment by amabunny** [comment]
Same issue as @dkeulen

**Comment by sneko** [comment]
@dkeulen @iamgreyy I think it could help you a bit #117

**Comment by auchenberg** [comment]
New version released and the readme for windows instructions have been updated. https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/releases/tag/v0.3.0

**Comment by dlong500** [comment]
I really appreciate the work people have done on this, but even following all the latest instructions I am unable to get things to work (the remote target never shows up in Chrome).  I'm using the v0.3.0 release.  My iOS version is 12.0.1, so I don't know if that breaks things yet again.  I'd really be grateful for any insight.
