### ISSUE TITLE
Windows: Unable to find devices

### ISSUE THREAD

**Issue by dotnetshadow** [RemoteDebug/remotedebug-ios-webkit-adapter#52]
I have installed the adapter on Windows 10, but no devices show up in Chrome 

Currently running ios 10.3 I have been able to get the ios_webkit_debug_proxy.exe working currently with the same setup on it's own. 

I have tried running the updated ios_webkit_debug_proxy.exe

But it keeps saying in chrome:
Remote Target #LOCALHOST

In the console I keep getting
iosAdapter.getTargets

![image](https://cloud.githubusercontent.com/assets/296247/24866559/d3332f70-1e4d-11e7-85fb-24a406fa0717.png)

**Comment by auchenberg** [comment]
Aha. Looks like some error handling aren't functioning as expected. Please note that iOS 10 on Windows might not work as the [ios-webkit-debug-proxy-win32](https://github.com/artygus/ios-webkit-debug-proxy-win32) project isn't up to date. https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter#windows

**Comment by auchenberg** [comment]
@dotnetshadow Can you try to download the newest release of `ideviceinfo.exe` and put into your `node_modules/vs-libimobile/lib/` folder?

https://github.com/elrhk/Libimobiledevice-idevicerestore-for-Windows

**Comment by dotnetshadow** [comment]
I updated the ideviceinfo.exe but I still don't see anything show up in chrome

![image](https://cloud.githubusercontent.com/assets/296247/24887677/f0a53dca-1ea0-11e7-9dfa-b54048000a95.png)

![image](https://cloud.githubusercontent.com/assets/296247/24887683/fbc10694-1ea0-11e7-958a-b144bab01c15.png)

**Comment by auchenberg** [comment]
Can you try enable diagnostics by setting `DEBUG=remotedebug` before running?  Ex: `DEBUG=remotedebug npm start` or `DEBUG=remotedebug remotedebug_ios_webkit_adapter`

**Comment by auchenberg** [comment]
I have pushed some better error handling to make the adapter exit if this happens. https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/commit/97a4229628095c1cd3fdad23cb7f599b3904a94a

**Comment by dotnetshadow** [comment]
This is before your latest changes

![image](https://cloud.githubusercontent.com/assets/296247/24893843/90a64d6e-1ec9-11e7-8fa3-7afb4c803506.png)

![image](https://cloud.githubusercontent.com/assets/296247/24893852/99b6aaa2-1ec9-11e7-9e43-f0f59865c0a3.png)

BTW I'm using Chrome 57

**Comment by auchenberg** [comment]
Ah. That looks to be the Windows issue I have referred in the README. You can try to download a newer binary of ios-webkit-debug-proxy-win32, and replace the exe in your node_modules folder

The error for your issue is here https://github.com/artygus/ios-webkit-debug-proxy-win32/issues/24

@artygus is working on bringing Windows builds of ios-webkit-debug-proxy to a better ship model, so I hope this can be resolved in the next coming weeks.

**Comment by dotnetshadow** [comment]
Ahh thanks, I actually did try with newer version of ios-webkit-debug-proxy which works on it's own then I tried installing in the node_modules directory but i had the same issue. 

I actually did read that issue before submitting this, and I did try the steps you suggested but couldn't get it working but I'll have another go at it

**Comment by dotnetshadow** [comment]
I used the same build of ios-webkit-debug-proxy-win32 referenced in your link, I can see that it works on it's own 
![image](https://cloud.githubusercontent.com/assets/296247/24895439/c2355ece-1ed3-11e7-9f4a-f71dd6463b77.png)


But when I run the remotedebug stuff it doesn't want to work
![image](https://cloud.githubusercontent.com/assets/296247/24895419/9d6132e4-1ed3-11e7-8dcd-9bb0f7dc3ee9.png)

Tried different versions of `ideviceinfo.exe` but still no go, maybe I'll just wait for a few weeks

Happy to do a remote team viewer with you if that helps

**Comment by auchenberg** [comment]
@dotnetshadow What timezone are you in? Happy to debug this over remote.

If you try to start `ios-webkit-debug-proxy-win32` directly, and goes to `http://localhost:9222/json`, what do you see?

**Comment by pfeigl** [comment]
Exactly the same problem here. Followed all the steps in this too (replacing  the ios-webkit-debug-proxy-win32 and stuff).

Here is the Output of the json you asked for:

```
[{
   "devtoolsFrontendUrl": "/devtools/devtools.html?ws=localhost:9222/devtools/page/1",
   "faviconUrl": "",
   "thumbnailUrl": "/thumb/http://192.168.178.101/",
   "title": "Application Title",
   "url": "http://192.168.178.101/",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/1",
   "appId": "PID:1346"
}]
```

**Comment by auchenberg** [comment]
@pfeigl This looks like ` ios-webkit-debug-proxy-win32` is working as expected. What happens when you run `DEBUG=remotedebug remotedebug_ios_webkit_adapter`?

**Comment by auchenberg** [comment]
Ping pong @dotnetshadow @pfeigl

**Comment by sneko** [comment]
Hey guys! @auchenberg  @dotnetshadow  @pfeigl 

I was facing the issue of a loop of empty getTargets so I decided to debug the package running...

The variable `devices `was always empty :( ... While the last version of https://github.com/google/ios-webkit-debug-proxy was able to find my iPhone. So I searched the direct link to install this lib (and to avoid scoop manager): 

https://downloads.sourceforge.net/project/ios-webkit-debug-proxy-win32/v1.7.1/ios-webkit-debug-proxy-1.7.1-x64-bin.zip

Just unzip, and put the whole directory in `remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\lib`. After you relaunch RemoteDebug it seems there is an unhandled error at the getDeviceVersion... And it's coming from the version getter. I didn't find a way to get the version so I just do the same as for the simulator, I "mock" it : 
_(I didn't find cases where this version number is useful for the debug, that's why I skipped this step)_
```
                    getter = this.getDeviceVersion(d.deviceId).then(v => {
                        d.version = v;
                        return Promise.resolve(d);
                    }).catch((err) => {
                        d.version = '9.3.0';
                        return Promise.resolve(d);
                    });

```

Ok now everything should work (at least for me 😄) ! But I'm still unable to list pages in my `chrome://inspect` 😢 .

The only solution I found is to launch RemuteDebug on the port 9222... and that's it! Finish! It works!

I hope it will help someone 😄 

Sorry if it's not the much conventionnal way and if a better one exists (don't hesitate to share). @auchenberg I think at least the version getter catch could help.

Have a good weekend!

**Comment by auchenberg** [comment]
Gotcha @Sneko, this makes sense! I'll add some error handling right away.

Did you go to chrome://inspect -> discover network targets -> configure -> add `localhost:9000` and then started the adapter?

**Comment by sneko** [comment]
@auchenberg 

I didn't know I was able to do that 😸 . Thanks!

Without talking about error handling, the new version of ios-webkit-debug-proxy is required for me to make it work.

**Comment by auchenberg** [comment]
New version released. I'm still working on finding a better way to ship `ios-webkit-debug-proxy

**Comment by kuncevic** [comment]
I had same issue and just downloaded the thing from here https://github.com/Devjam81/Libimobiledevice-idevicerestore-for-Windows and copy to `remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\lib\` then after I restarted the `remotedebug_ios_webkit_adapter --port=9000` I continuously getting an error in console: `error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]`. 
However ` chrome://inspect` works just fine. I can debug the iPad safari on my PC, the experience if quite laggy but I can deal with that.

**Comment by Spongman** [comment]
the current windows release is broken.

you should either remove support for windows, or update the included libmobiledevice binaries.

**Comment by auchenberg** [comment]
@spongman You are more than welcome to contribute to this project to help out.

**Comment by virajphadte84** [comment]
Hello , Im facing same issue today . It was working fine few days back .When I connect ipad no devices are shown for inspect.
ios version - 12.3.1 
windows - 10 
chrome version - 85
